# Specifies the network interface to use for the LocalIP readout
interface = "eth0"

# Lengthen uptime output
long_uptime = true

# Lengthen shell output
long_shell = true

# Lengthen kernel output
long_kernel = false

# Toggle between displaying the current shell or your user's default one.
current_shell = true

# Toggle between displaying the number of physical or logical cores of your processor.
physical_cores = true

# Disks to show disk usage for. Defaults to `["/"]`.
# disks = ["/", "/home/user"]

# Show percentage next to disk information
# disk_space_percentage = true

# Show percentage next to memory information
memory_percentage = true

# Themes should be placed in "$XDG_CONFIG_DIR/macchina/themes/<custom.toml>" with the theme name being <custom>.
theme = "eclipse"

# Displays only the specified readouts.
# Accepted values (case-sensitive):
#   - Host
#   - Machine
#   - Kernel
#   - Distribution
#   - OperatingSystem
#   - DesktopEnvironment
#   - WindowManager
#   - Resolution
#   - Backlight
#   - Packages
#   - LocalIP
#   - Terminal
#   - Shell
#   - Uptime
#   - Processor
#   - ProcessorLoad
#   - Memory
#   - Battery
#   - GPU
#   - DiskSpace
# 
show = [
  "Host",
  "Kernel",
  "Machine",
  "Distribution",
  "OperatingSystem",
  "DesktopEnvironment",
  "WindowManager",
  "Packages",
  "Terminal",
  "Shell",
  "DiskSpace",
  "Processor",
  "DiskSpace",
  "Uptime",
  "Battery",
]
